package com.example.finalprojectapp.dto;

import com.sun.istack.NotNull;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceDto implements Serializable {
    @Schema(description = "id customer", example = "74478911-6424-47a7-911c-0daa262144fa")
    private UUID id;
    @Schema(description = "Customer object, if is null will not associated a customer")
    private CustomerDto customer;
    @Schema(description = "Invoice Quantities object list, must not be null")
    @NotNull
    private List<InvoiceQuantityDto> invoiceQuantities;
    @Schema(description = "Invoice number, autogenerated", example = "1")
    private Integer invoiceNumber;

    @Schema(description = "date added modified",pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime dateAdded;

    @Schema(description = "last invoice date modified",pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime lastDateModified;
}
